services:
  - type: web
    name: doctor-appointment-api
    env: node
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
